### ISSUE TITLE
Date Time issue in Get-ConfigMgrCollectionEvalTimes

### ISSUE THREAD

**Issue by Stroell** [jonasatgit/scriptrepo#6]
When I run this script in my lab there is an issue with get-date

Might be related to my German regional settings

![image](https://user-images.githubusercontent.com/42348774/108965696-820fdf80-767d-11eb-9316-91d8670ac3f4.png)

**Comment by Stroell** [comment]
Looks like this is the issue:
![image](https://user-images.githubusercontent.com/42348774/108968098-a0c3a580-7680-11eb-8f46-5be84d8353a9.png)

**Comment by jonasatgit** [comment]
Schould be fixed in the current version. ConfigMgr logs have the following datetime string format: 'MM-dd-yyyy' which can cause issues when converted to datetime on systems with different formats like: 'dd-MM-yyyy'.
